**Data Preprocessing**

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [54]:
from google.colab import files
uploaded = files.upload()

Saving Churn_Modelling.csv to Churn_Modelling (1).csv


In [ ]:
import io
df2 = pd.read_csv(io.BytesIO(uploaded['Churn_Modelling.csv']))

In [75]:
df2.head(10)

RowNumber  CustomerId   Surname  ...  IsActiveMember EstimatedSalary Exited
0          1    15634602  Hargrave  ...               1       101348.88      1
1          2    15647311      Hill  ...               1       112542.58      0
2          3    15619304      Onio  ...               0       113931.57      1
3          4    15701354      Boni  ...               0        93826.63      0
4          5    15737888  Mitchell  ...               1        79084.10      0
5          6    15574012       Chu  ...               0       149756.71      1
6          7    15592531  Bartlett  ...               1        10062.80      0
7          8    15656148    Obinna  ...               0       119346.88      1
8          9    15792365        He  ...               1        74940.50      0
9         10    15592389        H?  ...               1        71725.73      0

[10 rows x 14 columns]

In [76]:
pd.get_dummies(df2["Geography"])

France  Germany  Spain
0          1        0      0
1          0        0      1
2          1        0      0
3          1        0      0
4          0        0      1
...      ...      ...    ...
9995       1        0      0
9996       1        0      0
9997       1        0      0
9998       0        1      0
9999       1        0      0

[10000 rows x 3 columns]

In [ ]:
x = df2.iloc[:, 3:13].values
y = df2.iloc[:, 13].values

In [78]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
labelencoder_X_1 = LabelEncoder()
x[:, 1] = labelencoder_X_1.fit_transform(x[:, 1])
labelencoder_X_2 = LabelEncoder()
x[:, 2] = labelencoder_X_2.fit_transform(x[:, 2])
onehotencoder = OneHotEncoder(categorical_features = [1])
x = onehotencoder.fit_transform(x).toarray()
x = x[:, 1:]

/usr/local/lib/python3.6/dist-packages/sklearn/preprocessing/_encoders.py:415: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/preprocessing/_encoders.py:451: DeprecationWarning: The 'categorical_features' keyword is deprecated in version 0.20 and will be removed in 0.22. You can use the ColumnTransformer instead.
  "use the ColumnTransformer instead.", DeprecationWarning)


In [60]:
x

array([[0.0000000e+00, 0.0000000e+00, 6.1900000e+02, ..., 1.0000000e+00,
        1.0000000e+00, 1.0134888e+05],
       [0.0000000e+00, 1.0000000e+00, 6.0800000e+02, ..., 0.0000000e+00,
        1.0000000e+00, 1.1254258e+05],
       [0.0000000e+00, 0.0000000e+00, 5.0200000e+02, ..., 1.0000000e+00,
        0.0000000e+00, 1.1393157e+05],
       ...,
       [0.0000000e+00, 0.0000000e+00, 7.0900000e+02, ..., 0.0000000e+00,
        1.0000000e+00, 4.2085580e+04],
       [1.0000000e+00, 0.0000000e+00, 7.7200000e+02, ..., 1.0000000e+00,
        0.0000000e+00, 9.2888520e+04],
       [0.0000000e+00, 0.0000000e+00, 7.9200000e+02, ..., 1.0000000e+00,
        0.0000000e+00, 3.8190780e+04]])

In [61]:
y

array([1, 0, 1, ..., 1, 1, 0])

**Splitting and Training**

In [ ]:
from sklearn.model_selection import train_test_split as tts

In [ ]:
xtrain, xtest, ytrain, ytest = tts(x, y, test_size=0.2, random_state = 0)

**Feature Scaling**

In [ ]:
from sklearn.preprocessing import StandardScaler as ss

In [ ]:
xtrain = ss().fit_transform(xtrain)

In [ ]:
xtest = ss().fit(xtest)

**ANN Building**

In [ ]:
import keras
from keras.models import Sequential
from keras.layers import Dense

In [ ]:
classifier = Sequential()

In [ ]:
# Adding the input layer and the first hidden layer
classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu', input_dim = 11))

# Adding the second hidden layer
classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu'))

# Adding the output layer
classifier.add(Dense(units = 1, kernel_initializer = 'uniform', activation = 'sigmoid'))

# Compiling the ANN
classifier.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

In [84]:
classifier.fit(xtrain, ytrain, batch_size = 10, epochs = 100)

Epoch 1/100
8000/8000 [==============================] - 2s 190us/step - loss: 0.5549 - acc: 0.7864
Epoch 2/100
8000/8000 [==============================] - 1s 142us/step - loss: 0.5279 - acc: 0.7960
Epoch 3/100
8000/8000 [==============================] - 1s 142us/step - loss: 0.5166 - acc: 0.7960
Epoch 4/100
8000/8000 [==============================] - 1s 143us/step - loss: 0.5121 - acc: 0.7960
Epoch 5/100
8000/8000 [==============================] - 1s 145us/step - loss: 0.5074 - acc: 0.7960
Epoch 6/100
8000/8000 [==============================] - 1s 140us/step - loss: 0.5050 - acc: 0.7960
Epoch 7/100
8000/8000 [==============================] - 1s 146us/step - loss: 0.5033 - acc: 0.7960
Epoch 8/100
8000/8000 [==============================] - 1s 146us/step - loss: 0.5016 - acc: 0.7960
Epoch 9/100
8000/8000 [==============================] - 1s 141us/step - loss: 0.5014 - acc: 0.7960
Epoch 10/100
8000/8000 [==============================] - 1s 140us/step - loss: 0.5011 - acc: 0.7960

**Prediction**

In [ ]:
ypred = classifier.predict(xtest)

In [89]:
ypred

array([[0.24853846],
       [0.24853846],
       [0.24853846],
       ...,
       [0.24853846],
       [0.24853846],
       [0.24853846]], dtype=float32)

In [90]:
ytest

array([0, 1, 0, ..., 0, 0, 0])

In [ ]:
ypred = (ypred > 0.75)

In [ ]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(ytest, ypred)

In [98]:
cm

array([[1595,    0],
       [ 405,    0]])